'use client'

import { useState, useCallback } from 'react'
import type { WorksheetSchema } from '@/types/worksheet'
import { generateWorksheetPdf } from '@/lib/utils/pdf-export'
import { downloadInteractiveHtml } from '@/lib/utils/html-worksheet-export'

interface WorksheetExportProps {
  worksheetTitle: string
  onExport?: () => void
  /** CSS selector for the element to capture. Defaults to the worksheet container. */
  targetSelector?: string
  /** Show "Generated by Formulate" branding in PDF footer. Defaults to true (free tier). */
  showBranding?: boolean
  /** Worksheet schema — required for interactive HTML export. If omitted, the HTML button is hidden. */
  schema?: WorksheetSchema
  worksheetDescription?: string | null
  worksheetInstructions?: string | null
}

export function WorksheetExport({
  worksheetTitle,
  onExport,
  targetSelector = '[data-worksheet-content]',
  showBranding = true,
  schema,
  worksheetDescription,
  worksheetInstructions,
}: WorksheetExportProps) {
  const [exporting, setExporting] = useState(false)

  const handlePdfExport = useCallback(async () => {
    setExporting(true)
    onExport?.()

    try {
      await generateWorksheetPdf({
        targetSelector,
        worksheetTitle,
        showBranding,
      })
    } catch (err) {
      console.error('PDF export failed:', err)
      window.print()
    } finally {
      setExporting(false)
    }
  }, [worksheetTitle, onExport, targetSelector, showBranding])

  const handlePrint = () => {
    onExport?.()
    window.print()
  }

  const handleHtmlExport = () => {
    if (!schema) return
    onExport?.()
    downloadInteractiveHtml(
      schema,
      worksheetTitle,
      worksheetDescription || undefined,
      worksheetInstructions || undefined,
    )
  }

  return (
    <div className="no-print flex items-center gap-2">
      {/* PDF download button */}
      <button
        type="button"
        onClick={handlePdfExport}
        disabled={exporting}
        className="inline-flex items-center gap-2 rounded-lg bg-primary-800 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-primary-900 disabled:opacity-60"
      >
        {exporting ? (
          <>
            <svg className="h-4 w-4 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
            </svg>
            Generating PDF…
          </>
        ) : (
          <>
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
            </svg>
            Download PDF
          </>
        )}
      </button>

      {/* Interactive HTML download button */}
      {schema && (
        <button
          type="button"
          onClick={handleHtmlExport}
          className="inline-flex items-center gap-2 rounded-lg border border-primary-200 bg-surface px-4 py-2 text-sm font-medium text-primary-700 transition-colors hover:bg-primary-50"
        >
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 17.25v1.007a3 3 0 01-.879 2.122L7.5 21h9l-.621-.621A3 3 0 0115 18.257V17.25m6-12V15a2.25 2.25 0 01-2.25 2.25H5.25A2.25 2.25 0 013 15V5.25m18 0A2.25 2.25 0 0018.75 3H5.25A2.25 2.25 0 003 5.25m18 0V12a9 9 0 11-18 0V5.25" />
          </svg>
          Interactive
        </button>
      )}

      {/* Print button */}
      <button
        type="button"
        onClick={handlePrint}
        className="inline-flex items-center gap-2 rounded-lg border border-primary-200 bg-surface px-4 py-2 text-sm font-medium text-primary-700 transition-colors hover:bg-primary-50"
      >
        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18.75 7.131A48.345 48.345 0 0012 6.882a48.346 48.346 0 00-6.75.25" />
        </svg>
        Print
      </button>
    </div>
  )
}
