'use client'

import { useState, useCallback } from 'react'

interface WorksheetExportProps {
  worksheetTitle: string
  onExport?: () => void
  /** CSS selector for the element to capture. Defaults to the worksheet container. */
  targetSelector?: string
}

export function WorksheetExport({
  worksheetTitle,
  onExport,
  targetSelector = '[data-worksheet-content]',
}: WorksheetExportProps) {
  const [exporting, setExporting] = useState(false)

  const handlePdfExport = useCallback(async () => {
    setExporting(true)
    onExport?.()

    try {
      // Dynamic imports — only loaded when user clicks export
      const html2canvas = (await import('html2canvas-pro')).default
      const { jsPDF } = await import('jspdf')

      const target = document.querySelector(targetSelector) as HTMLElement
      if (!target) {
        // Fallback to window.print() if no target found
        window.print()
        setExporting(false)
        return
      }

      // A4 dimensions in mm
      const A4_WIDTH_MM = 210
      const A4_HEIGHT_MM = 297

      // NHS hole-punch margins (from compliance doc)
      const MARGIN_LEFT = 20  // mm — hole-punch margin
      const MARGIN_RIGHT = 15
      const MARGIN_TOP = 15
      const MARGIN_BOTTOM = 12

      const contentWidth = A4_WIDTH_MM - MARGIN_LEFT - MARGIN_RIGHT
      const contentHeight = A4_HEIGHT_MM - MARGIN_TOP - MARGIN_BOTTOM

      // Capture the worksheet at 2x resolution for crisp output
      const canvas = await html2canvas(target, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
        // Remove shadows and borders for cleaner PDF
        onclone: (doc: Document) => {
          const el = doc.querySelector(targetSelector) as HTMLElement
          if (el) {
            el.style.boxShadow = 'none'
            el.style.border = 'none'
            el.style.borderRadius = '0'
            el.style.padding = '0'
          }
          // Hide any buttons or interactive elements
          doc.querySelectorAll('button, .no-print, [data-no-print]').forEach((btn) => {
            ;(btn as HTMLElement).style.display = 'none'
          })
        },
      })

      // Calculate scaling to fit content width
      const imgWidth = canvas.width
      const imgHeight = canvas.height
      const ratio = contentWidth / (imgWidth / 2) // /2 because scale=2

      const scaledHeight = (imgHeight / 2) * ratio // full height in mm

      // Create PDF
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      })

      // Add header on first page
      const addHeader = (pageNum: number, totalPages: number) => {
        pdf.setFontSize(8)
        pdf.setTextColor(153, 153, 153)
        pdf.text(worksheetTitle, MARGIN_LEFT, 8)
        pdf.text(
          `Page ${pageNum} of ${totalPages}`,
          A4_WIDTH_MM - MARGIN_RIGHT,
          8,
          { align: 'right' }
        )
        // Thin line under header
        pdf.setDrawColor(230, 230, 230)
        pdf.setLineWidth(0.2)
        pdf.line(MARGIN_LEFT, 10, A4_WIDTH_MM - MARGIN_RIGHT, 10)
      }

      // Add footer
      const addFooter = () => {
        pdf.setFontSize(7)
        pdf.setTextColor(180, 180, 180)
        pdf.text(
          `Generated by Formulate · ${new Date().toLocaleDateString('en-GB')}`,
          A4_WIDTH_MM / 2,
          A4_HEIGHT_MM - 6,
          { align: 'center' }
        )
      }

      // Calculate total pages needed
      const totalPages = Math.ceil(scaledHeight / contentHeight)

      // Render across pages
      for (let page = 0; page < totalPages; page++) {
        if (page > 0) pdf.addPage()

        addHeader(page + 1, totalPages)
        addFooter()

        // Calculate which portion of the canvas to render on this page
        const sourceY = (page * contentHeight / ratio) * 2 // *2 for scale
        const sourceHeight = Math.min(
          (contentHeight / ratio) * 2,
          imgHeight - sourceY
        )

        if (sourceHeight <= 0) break

        // Create a temporary canvas for this page slice
        const pageCanvas = document.createElement('canvas')
        pageCanvas.width = imgWidth
        pageCanvas.height = sourceHeight
        const ctx = pageCanvas.getContext('2d')
        if (!ctx) break

        ctx.drawImage(
          canvas,
          0, sourceY, imgWidth, sourceHeight,
          0, 0, imgWidth, sourceHeight
        )

        const pageImgData = pageCanvas.toDataURL('image/jpeg', 0.95)
        const pageHeight = (sourceHeight / 2) * ratio

        pdf.addImage(
          pageImgData,
          'JPEG',
          MARGIN_LEFT,
          MARGIN_TOP,
          contentWidth,
          pageHeight
        )
      }

      // Save the PDF
      const safeName = worksheetTitle
        .replace(/[^a-zA-Z0-9\s-]/g, '')
        .replace(/\s+/g, '-')
        .toLowerCase()
      pdf.save(`${safeName}.pdf`)
    } catch (err) {
      console.error('PDF export failed:', err)
      // Fallback to browser print
      window.print()
    } finally {
      setExporting(false)
    }
  }, [worksheetTitle, onExport, targetSelector])

  const handlePrint = () => {
    onExport?.()
    window.print()
  }

  return (
    <div className="no-print flex items-center gap-2">
      {/* PDF download button */}
      <button
        type="button"
        onClick={handlePdfExport}
        disabled={exporting}
        className="inline-flex items-center gap-2 rounded-lg bg-primary-800 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-primary-900 disabled:opacity-60"
      >
        {exporting ? (
          <>
            <svg className="h-4 w-4 animate-spin" fill="none" viewBox="0 0 24 24">
              <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
              <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
            </svg>
            Generating PDF…
          </>
        ) : (
          <>
            <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
            </svg>
            Download PDF
          </>
        )}
      </button>

      {/* Print button */}
      <button
        type="button"
        onClick={handlePrint}
        className="inline-flex items-center gap-2 rounded-lg border border-primary-200 bg-white px-4 py-2 text-sm font-medium text-primary-700 transition-colors hover:bg-primary-50"
      >
        <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.829c-.24.03-.48.062-.72.096m.72-.096a42.415 42.415 0 0110.56 0m-10.56 0L6.34 18m10.94-4.171c.24.03.48.062.72.096m-.72-.096L17.66 18m0 0l.229 2.523a1.125 1.125 0 01-1.12 1.227H7.231c-.662 0-1.18-.568-1.12-1.227L6.34 18m11.318 0h1.091A2.25 2.25 0 0021 15.75V9.456c0-1.081-.768-2.015-1.837-2.175a48.055 48.055 0 00-1.913-.247M6.34 18H5.25A2.25 2.25 0 013 15.75V9.456c0-1.081.768-2.015 1.837-2.175a48.041 48.041 0 011.913-.247m10.5 0a48.536 48.536 0 00-10.5 0m10.5 0V3.375c0-.621-.504-1.125-1.125-1.125h-8.25c-.621 0-1.125.504-1.125 1.125v3.659M18.75 7.131A48.345 48.345 0 0012 6.882a48.346 48.346 0 00-6.75.25" />
        </svg>
        Print
      </button>
    </div>
  )
}
