/**
 * Shared PDF generation logic.
 * Used by WorksheetExport (therapist side) and BlankPdfGenerator (client side).
 * NHS hole-punch compliant: 20mm left margin, 15mm right, 15mm top, 12mm bottom.
 */
export async function generateWorksheetPdf(options: {
  targetSelector: string
  worksheetTitle: string
  showBranding?: boolean
}): Promise<void> {
  const { targetSelector, worksheetTitle, showBranding = true } = options

  const html2canvas = (await import('html2canvas-pro')).default
  const { jsPDF } = await import('jspdf')

  const target = document.querySelector(targetSelector) as HTMLElement
  if (!target) {
    window.print()
    return
  }

  // A4 dimensions in mm
  const A4_WIDTH_MM = 210
  const A4_HEIGHT_MM = 297

  // NHS hole-punch margins
  const MARGIN_LEFT = 20
  const MARGIN_RIGHT = 15
  const MARGIN_TOP = 15
  const MARGIN_BOTTOM = 12

  const contentWidth = A4_WIDTH_MM - MARGIN_LEFT - MARGIN_RIGHT
  const contentHeight = A4_HEIGHT_MM - MARGIN_TOP - MARGIN_BOTTOM

  // Capture at 2x resolution for crisp output
  const canvas = await html2canvas(target, {
    scale: 2,
    useCORS: true,
    logging: false,
    backgroundColor: '#ffffff',
    onclone: (doc: Document) => {
      const el = doc.querySelector(targetSelector) as HTMLElement
      if (el) {
        el.style.boxShadow = 'none'
        el.style.border = 'none'
        el.style.borderRadius = '0'
        el.style.padding = '0'
      }
      // Hide buttons and interactive elements
      doc.querySelectorAll('button, .no-print, [data-no-print]').forEach((btn) => {
        ;(btn as HTMLElement).style.display = 'none'
      })
    },
  })

  const imgWidth = canvas.width
  const imgHeight = canvas.height
  const ratio = contentWidth / (imgWidth / 2)
  const scaledHeight = (imgHeight / 2) * ratio

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const addHeader = (pageNum: number, totalPages: number) => {
    pdf.setFontSize(8)
    pdf.setTextColor(153, 153, 153)
    pdf.text(worksheetTitle, MARGIN_LEFT, 8)
    pdf.text(
      `Page ${pageNum} of ${totalPages}`,
      A4_WIDTH_MM - MARGIN_RIGHT,
      8,
      { align: 'right' }
    )
    pdf.setDrawColor(230, 230, 230)
    pdf.setLineWidth(0.2)
    pdf.line(MARGIN_LEFT, 10, A4_WIDTH_MM - MARGIN_RIGHT, 10)
  }

  const addFooter = () => {
    if (!showBranding) return
    pdf.setFontSize(7)
    pdf.setTextColor(180, 180, 180)
    pdf.text(
      `Generated by Formulate · ${new Date().toLocaleDateString('en-GB')}`,
      A4_WIDTH_MM / 2,
      A4_HEIGHT_MM - 6,
      { align: 'center' }
    )
  }

  const totalPages = Math.ceil(scaledHeight / contentHeight)

  for (let page = 0; page < totalPages; page++) {
    if (page > 0) pdf.addPage()

    addHeader(page + 1, totalPages)
    addFooter()

    const sourceY = (page * contentHeight / ratio) * 2
    const sourceHeight = Math.min(
      (contentHeight / ratio) * 2,
      imgHeight - sourceY
    )

    if (sourceHeight <= 0) break

    const pageCanvas = document.createElement('canvas')
    pageCanvas.width = imgWidth
    pageCanvas.height = sourceHeight
    const ctx = pageCanvas.getContext('2d')
    if (!ctx) break

    ctx.drawImage(
      canvas,
      0, sourceY, imgWidth, sourceHeight,
      0, 0, imgWidth, sourceHeight
    )

    const pageImgData = pageCanvas.toDataURL('image/jpeg', 0.95)
    const pageHeight = (sourceHeight / 2) * ratio

    pdf.addImage(
      pageImgData,
      'JPEG',
      MARGIN_LEFT,
      MARGIN_TOP,
      contentWidth,
      pageHeight
    )
  }

  const safeName = worksheetTitle
    .replace(/[^a-zA-Z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .toLowerCase()
  pdf.save(`${safeName}.pdf`)
}
